In [148]:
# print a one dimensional array
import pandas as pd
ser_a = ['a','b','c','d','e','f']
ser_b = [1,2,3,4,5,6]
oned_array = pd.Series(ser_b, index=ser_a)
oned_array

a    1
b    2
c    3
d    4
e    5
f    6
dtype: int64

In [5]:
# Convert pandas seried to list
oned_list = oned_array.to_list()
oned_list

[1, 2, 3, 4, 5, 6]

In [ ]:
# Function for adding, subtracting, multiplying or dividing series
series_1 = pd.Series([1, 2, 3, 4, 5])
series_2 = pd.Series([5, 4, 3, 2, 1])

def df_func(ser_a, ser_b, act_ser):
    if act_ser == 'add':
        print(series_1.add(series_2))
    elif act_ser == 'sub':
        print(series_1.sub(series_2))
    elif act_ser == 'mul':
        print(series_1.mul(series_2))
    elif act_ser == 'div':
        print(series_1.div(series_2))

df_func(series_1, series_2, 'div')

In [236]:
# Comparing 2 series
series_1.compare(series_2)

self  other
0   1.0    5.0
1   2.0    4.0
3   4.0    2.0
4   5.0    1.0

In [ ]:
# Create series from a dictionary
sample_dict = {'a':1, 'b':2, 'c':3, 'd':4}
dict_ser = pd.Series(sample_dict)
dict_ser

In [40]:
# Convert Numpy arrray to a series
import numpy as np
np_array = np.random.randint(8, size=5)
# np_array
ser_np = pd.Series(np_array)
ser_np

0    5
1    7
2    5
3    6
4    4
dtype: int32

In [80]:
# Changing column data type from string to integer and return string as 'NaN'
list_1 = [100, 200, 'python', 300.12, 400]
l_ser = pd.Series(list_1)
# l_ser.dtype
# l_ser.astype(int, errors='ignore')
# l_ser.convert_dtypes(convert_integer=True, convert_string=False)
# l_ser.astype('Float32', errors='coerce')
upd_ser = pd.to_numeric(l_ser, errors='coerce')
upd_ser

0    100.00
1    200.00
2       NaN
3    300.12
4    400.00
dtype: float64

In [78]:
# Generate series from a dataframe
import random as rdm
# df_1 = pd.DataFrame({'col_1' : [1,2,3,4,7,11], 'col_2':[4,5,6,9,5,0], 'col_3':[7,5,8,12,1,11]})
# df_1
def generat_list(count_1: int):
    rand_list = []
    for i in range(0,count_1):
        rand_list.append(rdm.randint(1,9))
    return rand_list
df_1 = pd.DataFrame({'col_1' : generat_list(5), 'col_2': generat_list(5), 'col_3': generat_list(5)})
df_1['col_1']

pandas.core.frame.DataFrame

In [83]:
# Converting given series to a numpy array
l_ser.array

<NumpyExtensionArray>
[100, 200, 'python', 300.12, 400]
Length: 5, dtype: object

In [97]:
# Convert a series of lists to a list
list_1 = ['Red', 'Green', 'White']
list_2 = ['Red', 'Black']
list_3 = ['Yellow']
ser_list = pd.Series([list_1,list_2,list_3])
# ser_list
# ser_list.explode()
ser_list.apply(pd.Series).stack().reset_index(drop=True)

0       Red
1     Green
2     White
3       Red
4     Black
5    Yellow
dtype: object

In [146]:
# Sort a series
unsort_l = ['100', '400', 'python', '300.12', '200']
pd_ser = pd.Series(unsort_l)
# pd_ser
sort_ser = pd_ser.sort_values()
sort_ser

0       100
4       200
3    300.12
1       400
2    python
dtype: object

In [176]:
# Insert data into a series

# add_ser = pd_ser.add('php', fill_value=0)
# new_ser = pd_ser.add(add_ser, fill_value=0)
ser_1 = pd.Series(['100', '400', 'python', '300.12', '200'])
ser_2 = pd.Series(['php'])
new_ser1 = pd.concat([ser_1, ser_2], ignore_index=True)
ser_1._append(ser_2, ignore_index=True)
# print(new_ser1)
# new_ser2

0       100
1       400
2    python
3    300.12
4       200
5       php
dtype: object

In [187]:
# Use filter/where clause in series

list_1 = [x for x in range(1,11)]
ser_3 = pd.Series(list_1)
# ser_4 = ser_3.where(ser_3 < 6)
# ser_4 = ser_4.dropna
ser_4 = ser_3[ser_3 < 6]
ser_4

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [219]:
# Change order of index

ser_5 = pd.Series({'A':1,'B':2,'C':3,'D':4,'E':5})
# ser_5 = ser_5.reindex(index = rdm.shuffle(ser_5.index.to_list()))
idx_list = ser_5.index.to_list()
rdm.shuffle(idx_list)
ser_5 = ser_5.reindex(index = idx_list)
ser_5

A    1
E    5
C    3
B    2
D    4
dtype: int64

In [229]:
# Finding mean and standard deviation
# ser_3.std()
print(f"{ser_3.mean()} {ser_3.std()}")

5.5 3.0276503540974917


In [243]:
# Using sql 'minus' in series
ser_6 = pd.Series([x for x in range(1,6)])
ser_7 = pd.Series([x for x in range(2,11,2)])
# minus_ser = list(set(ser_6) - set(ser_7))
# pd.Series(minus_ser)
ser_6[~ser_6.isin(ser_7)]

0    1
2    3
4    5
dtype: int64

In [252]:
# Return rows from 2 series where rows are not matching in both series

# Method-1
ser_6[~ser_6.isin(ser_7)]._append(ser_7[~ser_7.isin(ser_6)], ignore_index = True)

# Method-2
union_ser = pd.Series(np.union1d(ser_6,ser_7))
intrsect_ser = pd.Series(np.intersect1d(ser_6,ser_7))
union_ser[~union_ser.isin(intrsect_ser)]

array([ 1,  2,  3,  4,  5,  6,  8, 10], dtype=int64)

In [292]:
# Calculate frequency of values in a series/Group by
rdm.seed(5)
ser_8 = pd.Series([rdm.randint(1,9) for i in range(0,40)])
ser_8.value_counts().sort_values(ascending=False)
ser_8.mode()

0    3
dtype: int64

In [313]:
# Update a series value if highest value is not matching
rdm.seed(71)
ser_9 = pd.Series([rdm.randint(1,5) for i in range(0,15)])
ser_10 = ser_9.astype(str)
ser_10[~ser_10.isin(ser_10.mode())] = 'Other'
ser_10
# ser_9.value_counts()
# print(ser_9.mode())

0     Other
1         5
2         5
3     Other
4     Other
5     Other
6     Other
7     Other
8     Other
9     Other
10        5
11    Other
12        5
13    Other
14        5
dtype: object

In [331]:
# Find index of elements which are multiple of 5
print(ser_9[ser_9 % 5 == 0].index)
# list_5 = list(ser_9[ser_9 % 5 == 0].index)
# list_5
# ser_10 = ser_9.where(ser_9 % 5 == 0)
# ser_10

Index([1, 2, 10, 12, 14], dtype='int64')


In [337]:
# Fetch values from a given position
list_6 = [2, 5, 6, 8]
# ser_9[list_6]
ser_9.take(list_6)

2    5
5    2
6    2
8    1
dtype: int64

In [380]:
# Inheritance
class A:
    def __init__(self, n):
        self.n = n

    def display(self):
        print(self.n)

class B(A):

    def __init__(self, a, b):
        self.b = b
        super().__init__(a)
        # A.__init__(self, n)
    def display_ch(self):
        print(self.b + 1)
    # def __init__(self, n, roll):
    #     self.roll = roll
    #     A.__init__(self, n)

In [382]:
obj_1 = B(23, 56)
obj_1.display()

23


In [386]:
# Reversing list
list_6 = [1, 2, 4]
list_7 = list(reversed(list_6))
list_7

[4, 2, 1]

In [402]:
# Fetch values based on index:
rdm.seed(5)
ser_11 = pd.Series(rdm.randint(1,9) for i in range(0,21))
list_8 = [int(i) for i in input().split()]
# list_8
ser_12 = ser_11.take(list_8)
ser_12

1     6
3     1
6     1
7     3
9     6
11    4
17    4
19    5
dtype: int64

In [452]:
rdm.seed(5)
ser_14 = pd.Series([rdm.randint(0,21) for i in range(0,21)])
ser_13 = pd.Series([19, 8, 14, 16, 1])
list_10 = [pd.Index(ser_14).get_loc(i) for i in ser_13]
# idx_1 = pd.Index(ser_14)
# print(idx_1)
# print(idx_1.get_loc(9))
# ser_14
# list_10 = [pd.Index(ser_14).get_loc(i) for i in ser_14.values if i in ser_13]
# list_10
print(pd.Index(ser_14))
print(pd.Index(ser_14).get_loc(0))

Index([19, 8, 11, 20, 16, 0, 14, 7, 20, 1, 5, 3, 11, 15, 7, 12, 17, 3, 18, 7,
       0],
      dtype='int64')
[False False False False False  True False False False False False False
 False False False False False False False False  True]


In [446]:
series1 = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
series2 = pd.Series([1, 3, 5, 7, 10])
# print("Original Series:")
# print(series1)
# print(series2)
pd.Index(series1)
# result = [pd.Index(series1).get_loc(i) for i in series2]
# print("Positions of items of series2 in series1:")
# print(result)

Index([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], dtype='int64')

In [459]:
# Modifying values in a series
ser_15 = pd.Series(['php','pyhton','java','c#'])
ser_15
for i,str in enumerate(ser_15):
    ser_15[i] = str[0].upper() + str[1:-1] + str[-1].upper()

ser_15

0       PhP
1    PyhtoN
2      JavA
3        C#
dtype: object

In [460]:
# Using lambda in a series
ser_16 = pd.Series(['php','pyhton','java','c#'])
ser_17 = ser_16.map(lambda x : len(x))
ser_17

0    3
1    6
2    4
3    2
dtype: int64

In [481]:
# Finding difference between consecutive elements
rdm.seed(5)
ser_17  = pd.Series(rdm.sample(range(0,340), 7))
# ser_17
list(ser_17.diff().diff())


[nan, nan, 241.0, 97.0, -212.0, -195.0, 481.0]

In [486]:
# Converting dated to datetime
ser_18 = pd.Series(['01 Jan 2015' ,'10-02-2016' ,'20180307' ,'2014/05/06' ,'2016-04-12' ,'2019-04-06T11:20'])
ser_19 = pd.to_datetime(ser_18,format='mixed')
ser_19

0   2015-01-01 00:00:00
1   2016-10-02 00:00:00
2   2018-03-07 00:00:00
3   2014-05-06 00:00:00
4   2016-04-12 00:00:00
5   2019-04-06 11:20:00
dtype: datetime64[ns]

In [517]:
# Return differnet date components from a series
print('Day of Month')
print(list(pd.to_datetime(ser_18,format='mixed').dt.day))

print('Day of Year')
print(list(pd.to_datetime(ser_18,format='mixed').dt.day_of_year))

print('day of week')
print(list(pd.to_datetime(ser_18,format='mixed').dt.day_name()))

Day of Month
[1, 2, 7, 6, 12, 6]
Day of Year
[1, 276, 66, 126, 103, 96]
day of week
['Thursday', 'Sunday', 'Wednesday', 'Tuesday', 'Tuesday', 'Saturday']


In [566]:
# Finding elements containing specific characters
import re
from collections import Counter
# Get values where 2 vowels are available
ser_20 = pd.Series(['Red' ,'Green' ,'Orange' ,'Pink' ,'Yellow' ,'White'])
# ser_20[ser_20.map(lambda x : )]
# SOLUTION 1
print(ser_20[ser_20.str.count('[aeiou]', re.I) >=2])
# SOLUTION 2
ser_21 = ser_20.map(lambda x : sum(Counter(x.lower()).get(i, 0) for i in list('aeiou')) >= 2)
print(ser_20[ser_21])
# Counter('Redd'.lower())

1     Green
2    Orange
4    Yellow
5     White
dtype: object
1     Green
2    Orange
4    Yellow
5     White
dtype: object


In [595]:
# Finding Eucladian distance
import math
ser_22 = pd.Series(list(range(1,11)))
ser_23 = pd.Series([11,8,7,5,6,5,3,4,7,1])
# Solution 1
print(math.sqrt(sum(ser_23.subtract(ser_22).multiply(ser_23.subtract(ser_22)))))
# Solution 2
print(np.linalg.norm(ser_22 - ser_23))

16.492422502470642
16.492422502470642


0   -10
1    -6
2    -4
3    -1
4    -1
5     1
6     4
7     4
8     2
9     9
dtype: int64

In [617]:
# Finding value with smaller neighbours
ser_25 = pd.Series([1 ,8 ,7 ,5 ,6 ,5 ,3 ,4 ,7 ,1])
# ser_25[-2]
# len(ser_25)
# SOLUTION 1
list_11 = []
for idx,val in enumerate(ser_25):
    if idx == 0 and val > ser_25[1]:
        list_11.append(idx)
    elif idx == len(ser_25)-1 and val > ser_25[idx-1]:
        list_11.append(idx)
    elif idx != 0 and idx != len(ser_25)-1 and val > ser_25[idx-1] and val > ser_25[idx+1]:
        list_11.append(idx)

# SOLUTION 2
print(ser_25)
print(np.diff(ser_25))
print(np.sign(np.diff(ser_25)))
temp = np.diff(np.sign(np.diff(ser_25)))
temp_1 = np.where(temp == -2)[0]
result = np.where(temp == -2)[0] + 1
print(result)

0    1
1    8
2    7
3    5
4    6
5    5
6    3
7    4
8    7
9    1
dtype: int64
[ 7 -1 -2  1 -1 -2  1  3 -6]
[ 1 -1 -1  1 -1 -1  1  1 -1]
[1 4 8]


In [659]:
# Replace string with least frequent character
str_1 = 'abc def abcdef icd'
# Solution 1
ser_26 = pd.Series(Counter(str_1))
print(ser_26)
idx_2 = pd.Index(ser_26.sort_values())[0]
str_2 = ser_26.index[ser_26 == idx_2].to_list()[0]
# print(idx_2)
print(str_1.replace(' ',str_2))

# Solution 2
ser_27 = pd.Series(list(str_1))
str_2 = ser_27.value_counts().dropna().index[-1]
result = "".join(ser_27.replace(' ',str_2))
result

a    2
b    2
c    3
     3
d    3
e    2
f    2
i    1
dtype: int64
abcidefiabcdefiicd


c    3
     3
d    3
a    2
b    2
e    2
f    2
i    1
Name: count, dtype: int64

In [715]:
rdm.seed(5)
ser_29 = pd.Series([round(rdm.uniform(-3, 20),6) for x in range(0,14)])
print(ser_29)
print([round(ser_29.autocorr(i),2) for i in range(11)])
# print(ser_29.autocorr())
# print(ser_30.autocorr())
# ser_29.autocorr()

# np.random.randn(5)

0     11.326739
1     14.061101
2     15.289452
3     18.676357
4     14.017667
5     18.213475
6     -2.332880
7      7.709321
8     18.697204
9     11.926415
10    17.720711
11    -0.396263
12     7.788588
13     2.671175
dtype: float64
[1.0, 0.02, 0.07, -0.37, -0.2, 0.43, 0.16, 0.49, -0.83, -0.28, -0.66]


In [37]:
# Display all the sundays of given year
import pandas as pd
import datetime as dtm
# start_date = dtm.datetime.strptime('2024-08-18','%Y-%m-%d')
# start_date
year_1 = input()
start_date = dtm.date.min.replace(year=int(year_1))
# for i in range(1,8):
    # if (start_date + pd.Timedelta(days=i)).weekday() == 6:
        # start_date = start_date + pd.Timedelta(days=i)
    #     break
    # else:
    #     continue
print(start_date)
print(start_date.weekday())
last_day = dtm.date.max.replace(year=int(year_1))
date_list = pd.date_range(start_date,last_day,freq='W-SUN')
date_series = pd.Series(date_list)
print(last_day)
print(date_list)
print(date_series)

2020-01-01
2
2020-12-31
DatetimeIndex(['2020-01-05', '2020-01-12', '2020-01-19', '2020-01-26',
               '2020-02-02', '2020-02-09', '2020-02-16', '2020-02-23',
               '2020-03-01', '2020-03-08', '2020-03-15', '2020-03-22',
               '2020-03-29', '2020-04-05', '2020-04-12', '2020-04-19',
               '2020-04-26', '2020-05-03', '2020-05-10', '2020-05-17',
               '2020-05-24', '2020-05-31', '2020-06-07', '2020-06-14',
               '2020-06-21', '2020-06-28', '2020-07-05', '2020-07-12',
               '2020-07-19', '2020-07-26', '2020-08-02', '2020-08-09',
               '2020-08-16', '2020-08-23', '2020-08-30', '2020-09-06',
               '2020-09-13', '2020-09-20', '2020-09-27', '2020-10-04',
               '2020-10-11', '2020-10-18', '2020-10-25', '2020-11-01',
               '2020-11-08', '2020-11-15', '2020-11-22', '2020-11-29',
               '2020-12-06', '2020-12-13', '2020-12-20', '2020-12-27'],
              dtype='datetime64[ns]', freq='W-SUN')


In [74]:
import random as rdm
rdm.seed(5)
# convert a series into dataframe with another column having values as index
ser_30 = pd.Series(rdm.randint(0,9) for i in range(0,5))
# print(rdm.randint(1,9))
list_12 = list(ser_30.index)
# print(ser_30.add(list_12))
# print(ser_30)
# df_2 = pd.DataFrame(ser_30)
# df_2["column_1"] = list_12
# df_2
ser_30
ser_31 = ser_30.reset_index()
print(ser_30)
print(type(ser_31))

0    9
1    4
2    5
3    8
4    0
dtype: int64
<class 'pandas.core.frame.DataFrame'>


In [72]:
import numpy as np
char_list = list('ABCDEFGHIJKLMNOP')
num_array = np.arange(8)
num_dict = dict(zip(char_list, num_array))
num_ser = pd.Series(num_dict)
print(char_list)
print(num_array)
print(num_dict)
print(num_ser)
df_2 = num_ser.to_frame().reset_index()
print(df_2)

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P']
[0 1 2 3 4 5 6 7]
{'A': 0, 'B': 1, 'C': 2, 'D': 3, 'E': 4, 'F': 5, 'G': 6, 'H': 7}
A    0
B    1
C    2
D    3
E    4
F    5
G    6
H    7
dtype: int32
  index  0
0     A  0
1     B  1
2     C  2
3     D  3
4     E  4
5     F  5
6     G  6
7     H  7


In [83]:
# stack to series in pandas horizintally
ser_32 = pd.Series(i for i in range(0,10))
ser_33 = pd.Series(list('pqrstuvwxy'))
ser_34 = pd.concat([ser_32, ser_33], axis = 1)
ser_34

0  1
0  0  p
1  1  q
2  2  r
3  3  s
4  4  t
5  5  u
6  6  v
7  7  w
8  8  x
9  9  y

In [95]:
# Check equality of series in pandas
rdm.seed(5)
ser_35 = pd.Series(rdm.randint(0,3) for i in range(0,10))
ser_36 = pd.Series(rdm.randint(0,3) for i in range(0,10))
print(ser_35)
print(ser_36)
print(ser_35.eq(ser_36))
# print(ser_35 == ser_36)

0    2
1    2
2    0
3    3
4    1
5    0
6    1
7    0
8    2
9    3
dtype: int64
0    1
1    3
2    0
3    1
4    0
5    1
6    3
7    2
8    1
9    3
dtype: int64
0    False
1    False
2     True
3    False
4    False
5    False
6    False
7    False
8    False
9     True
dtype: bool


In [114]:
# Find first occurance of largest and smallest value
print(ser_35)
print(ser_35.min())
print(ser_35.max())
print(ser_35.index[ser_35 == ser_35.min()].min())
print(ser_35.index[ser_35 == ser_35.max()].min())
print(ser_35.idxmax())
print(ser_35.idxmin())
# ser_35.index[ser_35 == ser_35.max()].min()

0    2
1    2
2    0
3    3
4    1
5    0
6    1
7    0
8    2
9    3
dtype: int64
0
3
2
3
3
2


In [136]:
# Check inequality between dataframe and series
# np.random.seed(5)
# arr_1 = np.random.randn(5, 4)
# arr_1[4,0] = 'NaN'
# df_3 = pd.DataFrame(arr_1)
df_data = pd.DataFrame({'W':[68,75,86,80,None],'X':[78,75,None,80,86], 'Y':[84,94,89,86,86],'Z':[86,97,96,72,83]});
sr_data = pd.Series([68, 75, 86, 80, None])
print(df_data)
print(sr_data)
print(df_data.ne(sr_data, axis = 0))

      W     X   Y   Z
0  68.0  78.0  84  86
1  75.0  75.0  94  97
2  86.0   NaN  89  96
3  80.0  80.0  86  72
4   NaN  86.0  86  83
0    68.0
1    75.0
2    86.0
3    80.0
4     NaN
dtype: float64
       W      X     Y     Z
0  False   True  True  True
1  False  False  True  True
2  False   True  True  True
3  False  False  True  True
4   True   True  True  True
